name: AI-based Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai
        pip install pygments

    - name: Run AI-based build script
      run: |
        python .github/workflows/ai_build.py
