name: Build Android App

on:

  push:

    branches:

      - main

  pull_request:

    branches:

      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository

      uses: actions/checkout@v2

    - name: Set up JDK 11

      uses: actions/setup-java@v2

      with:

        java-version: 11

        distribution: 'adopt'

    - name: Cache Flutter dependencies

      uses: actions/cache@v2

      with:

        path: /opt/flutter

        key: ${{ runner.os }}-flutter-${{ hashFiles('.github/workflows/build-android.yml') }}

        restore-keys: |

          ${{ runner.os }}-flutter-

    - name: Install Flutter

      run: |

        if ! [ -d /opt/flutter ]; then

          git clone https://github.com/flutter/flutter.git --branch stable --depth 1 /opt/flutter

        fi

        echo "/opt/flutter/bin" >> $GITHUB_PATH

        flutter config --no-analytics

    - name: Install dependencies

      run: |

        cd app

        flutter pub get

    - name: Build Android app

      run: |

        cd app

        flutter build apk --release

